### ISSUE TITLE
Solution Dev - VBScript for file transport

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-field-teams#127]

**Comment by rhood23699** [comment]
7/20/21 - Install on Dr. Reddy's DB server and a Scheduled Task was created.  When Staging has been completed and the RS Schema moved to Prod/Test, a client key will generated and updated in the VBScript, and then test files can be generated and sent to RS.

**Comment by hermanAlexCordero** [comment]
Installed VBScript Artifacts @ Dr Reddy's Workstation. on 7/20/2021

Repository of artifacts installed:
https://drive.google.com/drive/folders/1aNh6aBJI7zimSvJvFyFLtDjJcxGTrXWB?usp=sharing

**Comment by rhood23699** [comment]
Development is complete.  Testing will being as soon as we move to Prod/Test.  Target date is 8/6/21.
