### ISSUE TITLE
Reddy Family Medical Clinic - HL7 Onboarding

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-field-teams#148]
**_Standard Tasks / Onboarding Steps:_**

**Kickoff Meetings/Follow Up:**
**Solution Planning:**
          - Mapping
          - Brainstorming/Grooming
          - Complete RS Solution Feature Request (if needed)
**Solution Development:**
          - RS Schema
          - Other Dev (VBScript, etc)
**Solution Testing:**
          - Staging
          - Prod/Test
          - RS Feature Request (if needed)
          - Sender Acceptance w/ Client Signoff
**Solution Implementation:**
          - Plan & Schedule Go Live
          - GO LIVE and Post LIVE Review

**Comment by HeatherRienks** [comment]
8/12/21 - On hold for now.

**Comment by rhood23699** [comment]
Closing this EPIC.  We will not do HL7 onboarding with Reddy.  They will continue with the CSV process.
