### ISSUE TITLE
Coordinate communication with Iowa DOH

### ISSUE THREAD

**Issue by MikeC-A6** [CDCgov/prime-field-teams#188]

**Comment by HeatherRienks** [comment]
9/9/21 - Heather to connect with Receiver team on status of Iowa's onboarding.

**Comment by HeatherRienks** [comment]
9/10/21 - Ming will provide an update once she has confirmed with Iowa that they are ready to establish a connection with RS.

**Comment by HeatherRienks** [comment]
9/14/21 - Internal alignment meeting scheduled for 9/16/21 to discuss further.

**Comment by HeatherRienks** [comment]
9/22/21 - Confirmed that Iowa is NOT online with RS.
