### ISSUE TITLE
Solution Development - Other Dev (VBScript, etc.)

### ISSUE THREAD

**Issue by HeatherRienks** [CDCgov/prime-field-teams#217]
VBScript for CSV Cleanup and Uploading.  Took the Greenlight VBScript and make the following changes.

**Experity/Compass (CUC) Cleanup Functions Needed.**
 - Filter out non-COVID tests.
 - Set Ordering Provider NPI when they are blank, but we have the Ordering Provider Names. - Can't be done without an ELSE in RS.
 - Clear Date of Illness Onset when invalid values are received. - Clearing invalid date text could probably be done in RS, but we would need to talk with RS Team to see if OUR routine could be easily duplicated in an RS mapper.
- If patient state & zip are blank, then   ** Not sure if this can be done in RS, but ask the RS Team.
          - Set patient city, state & zip to the Ordering Facility city, state & zip.
          - Set patient address1 to "** No Address Given ***"
- Clear phone numbers set to "0".  patient, provider and facility phone #s.

**Folder Definitions & File Names**
Client CSV File Location: /Out  -  This is the CSV created by the Client.
Client CSV File Extension: .csv

Transformed CSV File Location: /Processed - The transformed CSV file is written to this Location.  This is a copy of what the VBScript sent to RS.
Transformed CSV File Extension: -transformed.csv

**Comment by rhood23699** [comment]
This is complete.  I'll open a new Issue to review all VBScript routines that could/should be moved to RS as soon as possible.
