### ISSUE TITLE
Solution Imp. - GO LIVE and Post LIVE Review

### ISSUE THREAD

**Issue by HeatherRienks** [CDCgov/prime-field-teams#223]
We will review files, make modifications if necessary, submit results, and work all errors until we are satisfied that the process is stable and ready to be turned over to the Sender.

**Comment by rhood23699** [comment]
9/7/21 - Missing zip codes are the main problem.  I'm creating pull requests and updating the zip code csv file when needed.

**Comment by rhood23699** [comment]
Sent results from 9/7/21 and 7/1/21 thru 7/31/21.

**Comment by rhood23699** [comment]
9/9/21 - Files are exporting encoded as UTF-8-BOM.  Modified the VBScript to remove the 1st three garbage characters.  Note, until the zip code stop failing, we'll manually submit and monitor errors.

**Comment by rhood23699** [comment]
Found the Healgen Scientific COVID-19 IgG/IgM Rapid Test results in the May and June 2021 backlog files.  We haven't coded for this, but before I start, I've asked Compass Urgent Care to verify whether or not this was performed in-house.

**Comment by rhood23699** [comment]
Compass states there are no other COVID tests that were performed in the past, so the schema updates will go in on Tuesday, 9/21/21.  I'll start uploading the Healgen Antibody backlog then.

**Comment by rhood23699** [comment]
Note, the missing Zip Codes is a big problem.  The Pipeline team doesn't really want us to turn off the patient_county error because they feel other states will reject their messages, but the out-of-date database is causing, so many errors, there is no way to turnover the sending and error processing to the client until this issue is fixed.

**Comment by rhood23699** [comment]
The pull request to add Healgen antibody was delayed until Thursday, 9/23.

Herman and Rick are working on a one-time updated to the Zip.CSV and FIPS County.CSV.  This should get us past the errors for now until either the Pipeline Team or Tools Team updates RS to utilize the SmartySheets API.

**Comment by rhood23699** [comment]
The zip download that Herman found has missing data also, so I'll post a message to Mo about a one-time download from usps.com

**Comment by rhood23699** [comment]
Working on initial draft of Customization Checklist and File Submission Process documents.  Target is to complete by 10/6/21, and setup training and hand-off for Friday the 8th or early next week.
