### ISSUE TITLE
Solution Testing - CSV File Cleanup VBScript

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-field-teams#224]
**Description:**
This is a client-side script to remove blank Rows, remove the Order Row, remove the Pregnant Row, and move the Pregnant Rows value to the Test Result Row.

**Folder Definitions:**
Client CSV File Location: /Out  -  This is the CSV created by the Client.
Client CSV File Extension: .csv

Cleaned CSV File Location: /Ready  - The new cleaned CSV file is written to this Location.  The VBScript for sending files should send all "-cleaned.csv" files in this Location.
Cleaned CSV File Extension: -cleaned.csv

Processed Client CSV File Location: /OriginalFiles  -  After the Client CSV file is processed, it is moved to this location.

**Phase I - VBScript Logic:**
Dim prevMRN as string
Dim prevPregnantValue as string

prevMRN = ""
prevPregnantValue = ""

For each Row in Client CSV
    IF FirstRow THEN Write the Header Row to the Cleaned File
    IF Left$(Row,4) = ",,,," THEN SKIP THIS ROW
    
    Split the Row into Columns
    IF trim( Column#19 / TestName ) <> "SARS-CoV-2 (COVID-19) Ag" THEN SKIP THIS ROW.
    IF Column#18 / LOINC = "NULL"  THEN SKIP THIS ROW.
    IF Column#18 / LOINC = "" THEN
          prevMRN = Column#2 / MRN
          prevPregnantValue = Column#20 / LabResult
          SKIP THIS ROW
    END IF

    IF Column#18 / LOINC = "94500-6" THEN
          Column#19 / TestName = trim( Column#19 / TestName )
          IF prevMRN = Column#2 / MRN THEN
                Column#39/ Pregnant = prevPregnantValue
          END IF
          prevMRN = ""
          prevPregnantValue = ""
          Write this Row with the new values to the Cleaned CSV File
   END IF

Next Row

Move Client CSV to /OriginalFiles

Exit VBScript
          

**Phase II - Improved Error Handling**

**Acceptance Criteria:**
- All non-COVID results are removed.   TestName ) <> "SARS-CoV-2 (COVID-19) Ag" THEN SKIP THIS ROW.
- Pregnancy Rows are removed and all Pregnancy values are inserted into the Result Row for the same MRN.
- Client CSV File is moved to /Original Files
- Cleaned CSV File is written to /Ready

**Comment by hermanAlexCordero** [comment]
Development started 8/10/2021  should be ready by end of 8/12/2021

**Comment by rhood23699** [comment]
8/11/21 - Created and sent Reddy test file to be used for CSV Cleanup Testing.

**Comment by rhood23699** [comment]
8/11/21 - De-identified around 20 Production results from Reddy's CSV file and sent to Herman to use for testing the CSV cleanup.

**Comment by rhood23699** [comment]
Email'd iPatientcare with our request to execute the iPatientcare stored procedure, so we can completely automate the process of running the report, exporting results, transforming/cleanup of data, and send the CSV to Agile Six.  Right now, this is a very time consuming daily manual process which involved iPatientcare and Agile Six personnel.

**Comment by rhood23699** [comment]
8/16/21 - iPatientcare not provide us with DB credentials to run the lab results stored procedure.  They stated that they will be working to write the SQL output to a CSV themselves.

**Comment by rhood23699** [comment]
8/16/21 - First draft of this VBScript is complete and tested.  There is one VBScript that can be used for de-identifying data, testing data transformation, and Production data transformation with RestAPI file transport functionality.

**Comment by rhood23699** [comment]
Closed this ticket.  The link to the Reddy notes on the VBScript is https://docs.google.com/document/d/1Rc7fYAPiXKAjjqThUA7tc3NCJdEbE1HrQf8dsdHbzUQ/edit

**Comment by rhood23699** [comment]
Herman is diagnosing why the script is not successfully sending files through the RestAPI.

In the meantime, I'll use this script to create the transformed file without sending it, and then use the original send a file only script to send the files to RS.

I'm leaving this ticket open until Herman completes debugging the send.

**Comment by rhood23699** [comment]
Added several cleanup and data transformations.  Send via the RestAPI is working.  Closing this issue.
