### ISSUE TITLE
Solution Development - VBScript

### ISSUE THREAD

**Issue by HeatherRienks** [CDCgov/prime-field-teams#265]
**Main Objectives & Tasks:**

- [ ] Modify the standard VBScript found at the link "****".  Modifications are typically related to Data Filtering, Data Transformation, Data Cleansing, and Transmission of the CSV file using the RS RestAPI.

- [ ] Perform and complete mainly unit and functional testing (ie. development, testing, and HL7 output) in the Local RS environment.

- [ ] Complete a code review with a fellow Interface Engineer.

**Comment by rhood23699** [comment]
N/A.  We will not use VBScript.  This Sender is one of our CSV Uploader Pilot site.
