### ISSUE TITLE
Create a checklist/process for how to engage new reporting entities.

### ISSUE THREAD

**Issue by smythe5** [CDCgov/prime-field-teams#29]
Initial draft checklist here - https://docs.google.com/document/d/1uUH7e2bZ9GA7zt-xJIDodjDI1p3z2cwS_4TGzc07POo/edit?usp=sharing

**Comment by Ben-Judy-Flexion** [comment]
I took a pass at creating a checklist [here](https://docs.google.com/document/d/1uUH7e2bZ9GA7zt-xJIDodjDI1p3z2cwS_4TGzc07POo/edit).

I left the initial brainstorm notes below.
