### ISSUE TITLE
Create a simple checklist that tells a reporting entity which fields are requiring for submission

### ISSUE THREAD

**Issue by smythe5** [CDCgov/prime-field-teams#34]
James is working on this.

The list provided by the CDC is confusing to comprehend for a non-technical confusion causing confusion for reporting entities.

This task is to make a simple, easy to understand version and make it a checklist. The checklist will be shared with reporting entities and used internally to evaluate CSV files.

The checklist should be created based on CDC requirements and then we can add state-specific fields as needed.

Acceptance Criteria: A single, simple to understand document that includes CDC and FLDOH requirements. The checklist should be printable and able to send electronically.

**Comment by HeatherRienks** [comment]
@smythe5, 
Would you like @rhood23699 to assist with this?

**Comment by smythe5** [comment]
@HeatherRienks - I think it would be great for @rhood23699 to check in with James Liu and see if this is still needed.  If not, then the card can be closed.

**Comment by HeatherRienks** [comment]
@rhood23699 - feel free to close out if this is not needed. See comment above.
Thanks!

**Comment by rhood23699** [comment]
I'm creating a Sender Automation specific reporting requirements document, so I'll use this Card.

**Comment by rhood23699** [comment]
Estimated completion by EOD on 7/9/21.

**Comment by rhood23699** [comment]
This was completed on 7/9/21, but since we will be taking on non-COVID, I will complete another document for all test types.

**Comment by rhood23699** [comment]
Closing this ticket.  Will open another ticket for non-COVID.
