### ISSUE TITLE
Identify Playbook Knowledge Base Tool

### ISSUE THREAD

**Issue by smythe5** [CDCgov/prime-field-teams#45]
**User Story:** As a production integration team member, I want a searchable knowledge base of reusable structures (links to code, artifacts, spreadsheets, templates, etc) so that I can find them easily.
**Description:** The intent of the playbook is to gradually “harvest” potentially reusable bits of structure that can be reused in other contexts. For instance, a spreadsheet describing additional fields required by a given state for ethnographic data collection might be useful in integrating other reporting entities in the state.
NOTE: Notion may be a good candidate, but we should run it through the AC to make sure it will work.

**Acceptance Criteria:**

- The knowledge base (KB) tool should provide a way of tagging or otherwise locating a given bit of potentially reusable structure across a variety of dimensions. For example, the state(s) it is relevant for, the nature of platform (such as Cerner or Epic), the type of structure (ex, code, artifact, template, etc). The exact tags/dimensions are described in a separate user story.

- The KB tool should be searchable.

- It should be easy to create documents and link to external documents.

- It should be easy to move things around and try different strategies for organizing information without significant rework or effort. For instance, if possible, moving a page should not break every link to that page.

- It should be possible to grant or restrict access to the KB based on permissions.

- If possible, when users perform a search they should be presented with a summary list of results, ordered by relevance.

- It should be possible to easily identify and group together related bits of structure into “plays.” 

- The KB should also support browsing related items.

- Ownership of knowledge repository should be able to be transferred to USDS at the end of the project. (This doesn’t mean that USDS needs to own or have a license for the tool now, but that there are not any significant barriers to transferring ownership — i.e. creating accounts, transferring admin rights, exporting to a different hosting environment, etc.).

- The KB tool has been selected and is ready to be used.

**Comment by ahay-agile6** [comment]
After doing research and demoing to the team, we decided to use Air Table as our knowledge base repository.
It follows all of the acceptance criteria and is free to use for our use case so far.
Here is the link to the one we started:
https://airtable.com/invite/l?inviteId=invsJmttJTrKXMF8S&inviteToken=40856a0d44ed99657e428d31689a4884f73538c2a53967b5147cd9f792716136
