### ISSUE TITLE
Create an initial information architecture/tagging structure for items added to the knowledge base

### ISSUE THREAD

**Issue by smythe5** [CDCgov/prime-field-teams#46]
**User Story:** As a production integration team member, I want an intuitive and coherent set of dimensions in terms of which plays and reusable elements can be located.

**Description:** We need an information architecture that can be used for locating KB items. For searching, this should be some kind of tag structure that locates each item in terms of a set of well-defined dimensions, such as state, technology platform, item type, etc. For browsing, it should be these dimensions organized into some kind of browsable hierarchy. I imagine this structure will continue to evolve, so we just need something to get us started.

**Acceptance Criteria:**

- The initial set of dimensions/tags should represent the most important and salient elements in terms of which reusable bits of structure can be identified.

- The tags have been presented to the team and they have had a chance to provide feedback.

IA / tagging taxonomy for playbook in a spreadsheet:
https://docs.google.com/spreadsheets/d/1lBnQflxpAeNXLWLDuEiSU-xoRCZtRP_U8PhMt1diaKM/edit#gid=0

**Comment by Ben-Judy-Flexion** [comment]
Started creating an IA / tagging taxonomy for playbook in a spreadsheet:
https://docs.google.com/spreadsheets/d/1lBnQflxpAeNXLWLDuEiSU-xoRCZtRP_U8PhMt1diaKM/edit#gid=0

Added link in [Notion playbook page](https://www.notion.so/agilesix/Playbook-57bca15b9dda43b4910c1955ae61c382).
