### ISSUE TITLE
FL-TPC Generate reporting workflow diagram 

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-field-teams#5]
Generate a workflow diagram that shows the workflow used by Tallahassee Primary Care to report on PCR and quick tests.

**Comment by Ben-Judy-Flexion** [comment]
Diagram: https://lucid.app/lucidchart/d6fabd8b-bb77-457b-b40a-78d620b30a9d/edit?page=-AWgfA83lAl7#?folder_id=home&browser=list
