### ISSUE TITLE
Identify data elements for RSSFE Registration

### ISSUE THREAD

**Issue by MikeC-A6** [CDCgov/prime-field-teams#59]
SimpleReport registration as a guide to determine which data elements should be collected at registration for Reportstream submitter front end.

Things to consider:

- What data elements might be useful to eliminate the need to include duplicative data in the CSV?  Example - facility information that never changes

**Acceptance Criteria:**  Spreadsheet of data elements to collect on registration with a description of how the data will be collected (ex. drop down, data validation)

**Comment by Ben-Judy-Flexion** [comment]
Spreadsheet with data elements from SimpleReport sign up form:
https://docs.google.com/spreadsheets/d/1vZSbvOPaTOq9A6QczRfDO709rO-FBO-7uEXDZaasdj8/edit#gid=0

**Comment by Ben-Judy-Flexion** [comment]
Here's a first pass at form fields & sections for RSSFE:
https://docs.google.com/spreadsheets/d/1vZSbvOPaTOq9A6QczRfDO709rO-FBO-7uEXDZaasdj8/edit#gid=1396745193
