### ISSUE TITLE
Map CLIA certification process for submitting entities

### ISSUE THREAD

**Issue by MikeC-A6** [CDCgov/prime-field-teams#63]
Intent is to understand the process for a submitter of COVID-19 test results to obtain a CLIA certification, so we can better understand potential options for onboarding submitters for ReportStream test result submission.  Is there identity verification that is required to get a CLIA number that could potentially be used for ID verification for a ReportStream front end?

**Comment by BerniXiongA6** [comment]
Hey @MikeC-A6 I'd be happy to be assigned to this issue, feel free to do so now that I have access to GitHub.

**Comment by BerniXiongA6** [comment]
Not sure how to mark this complete, but I've completed the task @MikeC-A6 . Will share the finished process mapping (high-level and detailed) in Notion. Here's a quick view of the high-level process mapped out.
[Current Process Mapping - CLIA Certification - Rev Jun.8.2021.pdf](https://github.com/CDCgov/prime-field-teams/files/6619731/Current.Process.Mapping.-.CLIA.Certification.-.Rev.Jun.8.2021.pdf)

**Comment by BerniXiongA6** [comment]
OK @MikeC-A6 looks like I have the correct rights now for GitHub, but I won't close this issue yet. We can discuss the process mapping first to make sure we got the info we need.
