### ISSUE TITLE
Talk to USDS about credentials for Experity

### ISSUE THREAD

**Issue by smythe5** [CDCgov/prime-field-teams#65]
- Would USDS want this direct access as part of ReportStream?
- Provide USDS with a write about the first bullet and meet to discuss
- Would need to get a BAA (can work with Dylan at iHealth Management to get it)

**Comment by HeatherRienks** [comment]
@smythe5 - does the Sender Automation team need to assist in any way with this request?

**Comment by smythe5** [comment]
@MikeC-A6 - is this something that still needs to be addressed?  If so, any suggestions on who could take lead?  It sounds like a good topic for you :)

**Comment by MikeC-A6** [comment]
@smythe5 - I think we are going to pause on this for now
