### ISSUE TITLE
Reorganize technical assistance folders in Google Drive

### ISSUE THREAD

**Issue by MikeC-A6** [CDCgov/prime-field-teams#68]

**Comment by HeatherRienks** [comment]
Rick and I made some changes to the folders on the Google drive.
Under the existing  PRIME DATA folder (https://drive.google.com/drive/folders/0AAvTSOtFXfz5Uk9PVA), we have a new folder called "Sender Automation Hub"
There are 3 folders nested here. (Sender Onboarding, Sender Production Issues, Senders - Completed Onboarding).

Within "Sender Onboarding" we have a folder for each submitter (GUC, Reddy).

And within each submitter, there are 3 subfolders (Solutions, Meetings & Emails, and Implementation).

We have moved a few docs to these new folders in an attempt to organize. If anyone has any feedback, please share!

**Comment by rhood23699** [comment]
Closing this card.  We'll continue to move directories and files into this structure as we find them.
