### ISSUE TITLE
For technical assistance, lay out team strategy planning sessions, retrospectives, and other ceremonies in a document.  Work with group to develop initial list / needs.

### ISSUE THREAD

**Issue by MikeC-A6** [CDCgov/prime-field-teams#70]

**Comment by rhood23699** [comment]
@HeatherRienks Began the initial draft using the Sender Automation Kanban Board document.  I'll move it a separate document later.  I plan to do an initial review with the Team on Monday, 6/28/21.

**Comment by HeatherRienks** [comment]
Team review of GitHub Sender Automation board completed today, 6/29/21.

**Comment by rhood23699** [comment]
This is mostly complete.  We'll leave it open for now because we know changes will be made based on things we learn as we move forward, especially with items related to Staging/Unit Testing and Integration Testing.

**Comment by rhood23699** [comment]
Heather is exploring whether or not we need to move to JIRA.

**Comment by rhood23699** [comment]
Heather and I are working on the conversion to ZenHub.  We'll review with the Team on Monday.

**Comment by HeatherRienks** [comment]
Reviewed new ZenHub board called "Prime Sender Automation" with team over past 2 standup meetings.

- Determined we will have ONE assignee per issue. 
-Team will self-assign all issues.

**Comment by rhood23699** [comment]
SA - Onboarding Process Guidance has been added to the Project Templates.  The document reference in this Issue is continually updated based on our experience with the 1st couple of onboard projects.
