### ISSUE TITLE
Greenlight Urgent Care (GUC)

### ISSUE THREAD

**Issue by HeatherRienks** [CDCgov/prime-field-teams#73]
**Kickoff & Delivery:**
 - [x]  Intro to the Sender by the State Health Dept
 - [x] Kickoff Meeting
 - [x]  Internal KO Meeting Review
  
**Solution Research & Planning:**
 - [x]  Solution Brainstorming Session
 - [x]  Solution Review / Grooming
 - [x]  Complete RS Solution/Feature Request (if needed)

**Solution Development:**
 - [ ]  SA - Complete RS Mapping & Client Signoff - In-Progess-6/23/21-REH
 - [ ]  SA - Complete RS Schema - In-Progress-6/23/21-REH
 - [ ]  SA - Complete Sender Specific Development (eg. Task Scheduling, Automation of CSV File Creation, VBScript Automated CSV File Upload)
 - [ ] Integration Testing (if needed)
 - [ ] RS - Feature Request Testing (if needed)
 - [ ] Sender Acceptance Testing & Training

**Solution Implementation:**
 - [ ]  Plan & Schedule GO LIVE
 - [ ]  Complete GO LIVE
 - [ ]  Post LIVE Monitoring
 - [ ] Project Retrospective

**Comment by rhood23699** [comment]
6/23/21 - Submitted the initial draft of Client Signoff question to Berni and had a call to review.  She is working on it now.

On 7/9/21, we have a call with Experity to re-establish contact, explain who we are and what we offer, and review outstanding questions because the project has been stalled since Dylan left.

**Comment by rhood23699** [comment]
**Solution Development:**
- Notes on the meeting are at https://docs.google.com/document/d/1nPKGAhXigkZ_FVo4ZNZiziiM1iyrdZcGB3pIDMSZkT4/edit
- David Hammond at Experity sent a new sample file based on the Standard Lab Report that he recommends we use.  Rick will start mapping COVID ASAP.
- This new file will have more than COVID, so Rick will also note changes needed for non-COVID results.

**Comment by rhood23699** [comment]
Requested changes and questions on the Standard Lap Report will be sent to David at Experity today.  Rick will begin mapping as much as possible today.
