### ISSUE TITLE
Reddy Family Medical Clinic - CSV Onboarding

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-field-teams#77]
**Kickoff & Delivery:**
 - [x]  Intro to the Sender by the State Health Dept
 - [x]  Kickoff Meeting 
 - [x]  Internal KO Meeting Review
  
**Solution Research & Planning:**
 - [x]  Solution Brainstorming Session
 - [ ]  Solution Review / Grooming - In-Progress-6/30/21-REH
 - [ ]  Complete RS Solution/Feature Request (if needed) - N/A

**Solution Development:**
 - [ ]  SA - Complete RS Mapping & Client Signoff - In-Progress-6/30/21-REH
 - [ ]  SA - Complete RS Schema - In-Progress-7/6/21-JB
 - [ ]  SA - Complete Sender Specific Development (eg. Task Scheduling, Automation of CSV File Creation, VBScript Automated CSV File Upload) - Pending-7/7/21-REH
 - [ ] Integration Testing (if needed)
 - [ ] RS - Feature Request Testing (if needed)
 - [ ] Sender Acceptance Testing & Training

**Solution Implementation:**
 - [ ]  Plan & Schedule GO LIVE
 - [ ]  Complete GO LIVE
 - [ ]  Post LIVE Monitoring
 - [ ] Project Retrospective

**Comment by rhood23699** [comment]
Yesterday, we received a CSV test file with PHI & PII.  This was reported and all copies of the file and emails have been deleted.

**Comment by rhood23699** [comment]
We received a new clean CSV test file.  I've reviewed and complete my initial set of questions.  The Team is reviewing and we'll email the questions on Monday.

**Comment by rhood23699** [comment]
Completed initial draft of the Reddy Mapping.
Completed draft of our response and additional questions for iPatientCare.

**Comment by jbiskie** [comment]
Completed initial draft of Reddy schema

**Comment by rhood23699** [comment]
7/6/21 & 7/7/21 - Our Team had a call with Vinit to address our outstanding questions on the CSV file and submission.  Multiple emails have been exchanged but a summary is:

- HL7 is the final solution for Reddy because it can be produced automatically by iPC.  I've created another CARD/ISSUE for HL7.
- We'll continue working on the CSV as a temporary solution to get Reddy online as quickly as possible.
- Vinit is checking on status of including the accession_no and what is causing NULL in the CSV result.
- Vinit is checking on whether or not they will need a VBScript from us for file transport.
- Revise Reddy Mapping & Schema based on RS Pipeline's training on Schemas and Mappers.  Scheduled for 7/8/21.

**Comment by rhood23699** [comment]
Team meet to modify the Mapping based on RS Schema training.  The Map will be updated today.  Summary:

- Do not map Abnormal Flag.  It is generated based on the result.
- Set Message ID to Accession Number + Test Performed LOINC Code.
- Set Device ID, and Joel is verifying that all LOINC and Description fields in the OBR and OBX will be set based on the Device ID alone.
- Remove Non Reactive and Reactive result SNOMED coding.
- Add Invalid Test and Inconclusive Test to the result SNOMED coding.
- Add Links in GitHub to all documents especially the Mapping Document.

**Comment by rhood23699** [comment]
Link to Mapping Document - https://docs.google.com/spreadsheets/d/1SzB8MxeVOYDjBECfHR82525KD40pIPjh/edit#gid=2083770358

**Comment by rhood23699** [comment]
**Solution Development**
- We will install a VBScript for CSV file transport.
- Accession No will not be sent, so we'll have to generate one.

**Comment by rhood23699** [comment]
7/13/21 - Reddy is the top priority to right now.  We had RS training today which applies to all Senders, but we focused on getting RS up on our laptops using Reddy as the test Sender as the first step for testing.  See meeting notes at https://docs.google.com/document/d/12ZPSznrXWCWDs03y1fn4YcKp8vGjXReu-YSbaEOUZwg/edit

**Comment by rhood23699** [comment]
Closed this issue.  The Reddy CSV Onboarding is now an EPIC on our ZenHub Board.
