### ISSUE TITLE
COVID Result SNOMED Coding

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-field-teams#80]
Below is the current logic for COVID result SNOMED coding.  Sender Automation will be coding results almost exclusively from the text given to us.  Almost all COVID results listed in the CMS LIVD spreadsheet have Negative coded as Not Detected instead Negative, and Positive coded as Detected instead of Positive.

First question, should we SNOMED code results based on the LIVD spreadsheet or based on the text provided in the Sender's file??  I can speak for several States that it doesn't matter to them, but should we code as close to the CMS specs as possible??

Second, are all of the SNOMED codes listed below in ReportStream??  The link https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/schema_documentation/covid-19.md does list Not Reactive or Reactive.

- IF Source in (Negative, Neg) THEN
          - RS.test_result = "260385009"
  - ELSEIF Source in (Positive, Pos) THEN
          - RS.test_result = "10828004"
 - ELSEIF Source in (Detected, DET) THEN
          - RS.test_result = "260373001"
  - ELSEIF Source in (Not Detected, NDET) THEN
          - RS.test_result = "260415000"
 - ELSEIF Source in (Reactive) THEN
          - RS.test_result = "11214006"
  - ELSEIF Source in (Not Reactive, Non-Reactive, Non Reactive) THEN
          - RS.test_result = "131194007"
  - ELSE
          - RS.test_result = ""
  - END IF

**Comment by jbiskie** [comment]
The input schema for SimpleReport data accepts SNOMED test_result_codes.  https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md

I didn't get a hit for the Reactive or Not Reactive codes anywhere in the RS repo.

**Comment by rhood23699** [comment]
I believe we'll have to remove Reactive and Non Reactive.

**Comment by rhood23699** [comment]
For now, I'll remove Non Reactive and Reactive from all mappings.
