### ISSUE TITLE
RS Access for Sender Automation team (on local machines)

### ISSUE THREAD

**Issue by HeatherRienks** [CDCgov/prime-field-teams#82]
Need assistance with access to Report Steam for necessary team members.

Up and running with RS on local machine:

 [X] Joel completed on 7.13.21
 [X] Herman completed on 7.14.21
 [X] Rick - completed on 7.13.21

**Comment by HeatherRienks** [comment]
Meeting scheduled with Aurora Hayes for 7/7/21 to walk team through how to add Report Stream to their Windows based machines.

**Comment by HeatherRienks** [comment]
Sender Automation team met with Jim Duff today to get Joel up and running on RS.

**Comment by HeatherRienks** [comment]
Rick has confirmed that he has successfully installed RS on his local machine as of 7/13/21.

Will confirm with Herman when he returns tomorrow.

**Comment by hermanAlexCordero** [comment]
RS Installed in my local machine and initial test of the VB Script is successful.
