### ISSUE TITLE
Setup RS Staging Training

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-field-teams#87]

**Comment by rhood23699** [comment]
7/12/21 - There was no agenda.  We requested a meeting with JimD and Anshul to review and schedule our request for Staging and Production/Testing Training.  Notes from the meeting are at https://docs.google.com/document/d/12ZPSznrXWCWDs03y1fn4YcKp8vGjXReu-YSbaEOUZwg/edit

We received training on how to setup and test a schema on our local versions of RS before moving to Staging.  Once testing is completed locally, we'll request Staging training through Anshul.

**Comment by HeatherRienks** [comment]
Training set for 7/23/21 with Carlos Felix.

**Comment by rhood23699** [comment]
Completed training.  A daily followup has been schedule to assist and answer questions.
